"""add_supervisor_memberships_and_primary_steward

Revision ID: 3ee990ffd925
Revises: 1c858dc756fe
Create Date: 2026-02-01 19:30:52.440173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee990ffd925'
down_revision = '1c858dc756fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PI', 'STEWARD', 'RESEARCHER', name='supervisorrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supervisor_id', 'user_id', name='uq_supervisor_user')
    )
    op.create_index('ix_supervisor_membership_supervisor_user', 'supervisor_memberships', ['supervisor_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_supervisor_memberships_id'), 'supervisor_memberships', ['id'], unique=False)
    # Use batch mode for SQLite FK support
    with op.batch_alter_table('supervisors') as batch_op:
        batch_op.add_column(sa.Column('primary_steward_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_supervisor_primary_steward', 'users', ['primary_steward_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisors') as batch_op:
        batch_op.drop_constraint('fk_supervisor_primary_steward', type_='foreignkey')
        batch_op.drop_column('primary_steward_user_id')
    op.drop_index(op.f('ix_supervisor_memberships_id'), table_name='supervisor_memberships')
    op.drop_index('ix_supervisor_membership_supervisor_user', table_name='supervisor_memberships')
    op.drop_table('supervisor_memberships')
    # ### end Alembic commands ###
