"""add_supervisor_db_dsn

Revision ID: 1c858dc756fe
Revises: 9863b775529e
Create Date: 2026-02-01 15:50:25.726657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c858dc756fe'
down_revision = '9863b775529e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supervisors', sa.Column('supervisor_db_dsn', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supervisors', 'supervisor_db_dsn')
    # ### end Alembic commands ###
